// SPDX-FileCopyrightText: Copyright 2026 eden-ios contributors
// SPDX-License-Identifier: GPL-3.0-or-later
//
// Derived from suyu's src/libretro_core/retro_core.cpp (suyu-emu/suyu-v0.0.4),
// GPL-3.0-or-later, which derives from yuzu (GPL-2.0-or-later).
// SPDX-FileCopyrightText: Copyright 2024 suyu Emulator Project
// SPDX-FileCopyrightText: Copyright 2018 yuzu Emulator Project

#pragma once

#include <cstddef>
#include <filesystem>
#include <string>

#include "core/core.h"

// WHERE EDEN ACTUALLY READS KEYS AND FIRMWARE
//
// Every path below is <root>-relative, where <root> is the directory handed to
// eden_libretro_set_data_root(). None of it is guessed; each line cites the code that
// opens the file. The user supplies all of it. Nothing in this port ships, downloads,
// generates or unlocks keys, firmware or games, and this translation unit performs no
// network access of any kind.
//
//   KEYS - Common::FS::EdenPath::KeysDir, i.e. <root>/keys.
//     KeyManager::ReloadKeys (key_manager.cpp:563-581) opens, in this order:
//       prod.keys_autogenerated, prod.keys      (dev.keys_* instead, when
//                                                Settings::values.use_dev_keys is set)
//       title.keys_autogenerated, title.keys
//       console.keys_autogenerated, console.keys
//     Later files win on conflict, so prod.keys overrides prod.keys_autogenerated.
//     A missing file is skipped silently (LoadFromFile early-returns,
//     key_manager.cpp:589-592) - there is no "wrong filename" diagnostic anywhere.
//     KeysDir must stay WRITABLE: derived keys are written back as *.keys_autogenerated.
//     key_retail.bin lives in the same directory but is read only by the amiibo path
//     (amiibo_crypto.cpp:284, :307); it never affects whether a game runs.
//
//   FIRMWARE - <root>/nand/system/Contents/registered, as flat NCA files.
//     FileSys::BISFactory builds the system-NAND RegisteredCache over exactly that
//     directory (bis_factory.cpp:19-20). RegisteredCache only sees files whose names
//     are 32 hex digits plus ".nca" or ".cnmt.nca" (registered_cache.cpp:56-63), either
//     directly in that directory or one level down inside a "000000XX" bucket
//     (registered_cache.cpp:622-655). Any other name is invisible to it, which is why
//     the user must extract a firmware archive WITHOUT renaming anything.
//
//   IMPORT DROP-OFF - <root>/keys_import. Not an Eden concept; this port's own. The app
//     writes an imported key file here and AdoptKeys() copies it into <root>/keys.
//
// WHAT FAILS, AND HOW
//   No keys at all: Core::System::Load returns ErrorLoader + ErrorMissingProductionKeyFile
//     for XCI/NSP/NAX (xci.cpp:77, nsp.cpp:116, nax.cpp:55); other paths surface as
//     ErrorMissingHeaderKey / ErrorMissingKeyAreaKey. DescribeLoadFailure() decodes them.
//   Stale keys (a prod.keys older than the content): the header key is present so the
//     file looks fine, but KeyManager::BaseDeriveNecessary (key_manager.cpp:692-710)
//     still reports keys missing because a master/key-area/titlekek pair for a newer
//     crypto revision is absent. This is the case a bare "does prod.keys exist?" check
//     gets wrong, and why Status distinguishes NoKeys from BadKeys.
//   No firmware: NOTHING reports it at load time. Core::SystemResultStatus::ErrorSystemFiles
//     and ErrorSharedFont (core.h:137-138) are declared and returned by no code in src/.
//     Missing firmware shows up later as a service failure inside the guest. That is the
//     whole reason for the pre-load firmware check below.
//
// THREADING AND SIDE EFFECTS
//   None of this is synchronised, and it cannot be: it reads globals
//   (LibretroCore::g_data_root_override, g_environ_cb), Common::FS's EdenPath table, and
//   the process-wide Core::Crypto::KeyManager singleton, none of which has a lock.
//   Call these from the one dedicated core thread described in
//   src/ios/Bridge/EdenCoreBridge.h, or from anywhere BEFORE that thread starts - never
//   concurrently with a load. SetupUserPaths(), AdoptKeys() and Describe() all WRITE:
//   they create directories, and AdoptKeys/Describe can reload the keyring.
//   Called before Common::Log::Initialize(), their logging goes nowhere; the return
//   values are still correct.

namespace LibretroCore::Content {

/// What the user still has to do before a game will run.
///
/// This is a *pre-load* judgement made entirely from disk and from the KeyManager
/// keyring. It is not a prediction that a particular ROM will load: a ROM can still
/// fail with a per-title key error (see DescribeLoadFailure) while the status here
/// says Ready.
enum class Status {
    /// No writable data root is known, so nothing can be checked or installed.
    /// Only reachable when eden_libretro_set_data_root() was never called AND the
    /// libretro frontend supplied no system directory.
    NoDataRoot,
    /// No prod.keys (or dev.keys, when Settings::values.use_dev_keys is set) exists
    /// in the keys directory. Nothing encrypted can be opened at all.
    NoKeys,
    /// The key file exists but the keyring it produced is incomplete: Eden could not
    /// derive every master/key-area/titlekek pair it needs, or the header key is
    /// absent. In practice this is a truncated file, a file for an older firmware
    /// generation, or a file whose lines Eden's parser rejected.
    BadKeys,
    /// Keys are complete; the emulated system NAND holds no firmware NCAs.
    /// NOT a blocker - most titles boot without firmware. Report it, do not refuse.
    NoFirmware,
    /// Keys are complete and firmware NCAs are present.
    Ready,
};

/// Every directory the user is ever told about, resolved against the root that was
/// actually applied to Common::FS's EdenPath table - not against whatever
/// eden_libretro_set_data_root() was handed most recently. When `valid` is false the
/// root was never applied and every path below is empty.
struct Paths {
    bool valid;
    std::filesystem::path root;            ///< EdenPath::EdenDir
    std::filesystem::path keys_dir;        ///< EdenPath::KeysDir - where Eden READS keys
    std::filesystem::path keys_import_dir; ///< <root>/keys_import - the drop-off AdoptKeys drains
    std::filesystem::path firmware_dir;    ///< <NANDDir>/system/Contents/registered
    /// Full path of the base key file Eden will actually read, i.e. keys_dir/"prod.keys",
    /// or keys_dir/"dev.keys" when Settings::values.use_dev_keys is set.
    std::filesystem::path base_key_file;
};

/// Everything the iOS UI needs to say something true about setup state.
struct Report {
    Status status;
    Paths paths;
    /// The base key FILE is on disk (prod.keys, or dev.keys under use_dev_keys).
    bool base_key_file_present;
    /// title.keys is on disk. Optional: only personalised/eShop dumps need it.
    bool title_key_file_present;
    /// key_retail.bin is on disk. Amiibo only; never affects whether a game runs.
    bool amiibo_key_file_present;
    /// The keyring derived from those files is complete
    /// (!KeyManager::BaseDeriveNecessary(), key_manager.h:285).
    bool keys_usable;
    /// Number of files under firmware_dir whose names match the NCA-id format the
    /// RegisteredCache scans for. 0 means no firmware.
    std::size_t firmware_nca_count;
};

/// Point every Common::FS::EdenPath at a writable root and create the directories.
///
/// Idempotent, and - unlike the original - NOT latched: if the resolved root changes
/// (the app calls eden_libretro_set_data_root() after retro_init has already run) the
/// table is re-pointed to the new root. Returns false only when no root has ever been
/// applied and none can be resolved now.
bool SetupUserPaths();

/// The root that is actually installed in the EdenPath table, or empty if none is.
/// This is the single source of truth every other function here resolves against.
const std::filesystem::path& AppliedRoot();

/// Copy key files out of <root>/keys_import into Eden's key directory, then reload the
/// KeyManager. Calls SetupUserPaths() first, so it can never disagree with it about
/// where the data root is.
void AdoptKeys();

/// !Core::Crypto::KeyManager::Instance().BaseDeriveNecessary() (key_manager.h:285).
/// True means the keyring is complete enough to open retail content.
bool KeysPresent();

/// Resolve the user-facing directories. Cheap; touches no disk.
Paths GetPaths();

/// Count firmware NCAs sitting in <NANDDir>/system/Contents/registered.
///
/// A filesystem scan, deliberately: it needs no Core::System, no keys and no
/// RegisteredCache, so it answers at app launch, before anything is loaded. It counts
/// *names*, so it cannot tell a valid NCA from a corrupt one - see
/// FirmwareRegistered() for the check that actually parses.
std::size_t CountFirmwareNcas();

/// CountFirmwareNcas() != 0.
bool FirmwarePresent();

/// The strict firmware check, equivalent to FirmwareManager::CheckFirmwarePresence
/// (frontend_common/firmware_manager.h:66-82) but without linking frontend_common:
/// asks the system NAND RegisteredCache for the Mii Edit applet's program NCA.
///
/// Requires that FileSystemController::CreateFactories() has already run on this
/// system and that keys are loaded, because the cache parses NCA headers to build its
/// index. Returns false, rather than failing, when the factories do not exist yet.
/// It does go through FileSys::NCA parsing, which this port has never executed on a
/// real firmware dump, so treat a false from it as "could not confirm", not as proof.
/// Use this after a load; use CountFirmwareNcas() before one.
bool FirmwareRegistered(Core::System& system);

/// Full pre-load status. Runs the disk checks every time it is called; there is no
/// caching, because the user can drop a file in from Files.app between two calls.
///
/// NOT a pure query: it calls SetupUserPaths() first (so the paths it reports are the
/// paths Eden will use, even if it is called before retro_init), which creates the data
/// directories; and when a key file is on disk but the keyring is unusable it reloads
/// the KeyManager once, so a key dropped in through Files.app is picked up.
Report Describe();

/// Stable, lowercase, machine-readable token for a status: "no_data_root", "no_keys",
/// "bad_keys", "no_firmware", "ready". Meant for a frontend to switch on. Never null.
const char* StatusToken(Status status);

/// One or two sentences a human can act on, naming the real path the file must go to.
std::string DescribeStatus(const Report& report);

/// RETRO_REGION_NTSC or RETRO_REGION_PAL, derived from Settings::values.region_index.
unsigned RetroRegion();

/// Human-readable form of the composite status Core::System::Load returns.
std::string DescribeLoadFailure(Core::SystemResultStatus status);

} // namespace LibretroCore::Content
